services:
  postgres:
    networks:
      - private
      - public
    ports:
      - "5432:5432"

  pgweb:
    image: sosedoff/pgweb:latest
    command:
      - "--listen=8082"
      - "--url=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable"
    ports:
      - "8082:8082"
    networks:
      - public
    depends_on:
      - postgres